sudo: required
dist: trusty
language: python
python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
matrix:
  allow_failures:
    - python: '2.7'
addons:
  apt:
    packages:
    - libattr1-dev
    - libfuse2
    - libfuse-dev
    - python-dev
    - python3-dev
install:
    - pip install --upgrade pip
    - pip --version
    - pip install 3to2 future
    - pip install -e .[all]
script: ./testall.sh
