language: python
python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
addons:
  apt:
    packages:
    - libattr-dev
    - libfuse-dev
install:
    - pip install --upgrade pip
    - pip --version
    - pip install 3to2 future
    - pip install -e .[all]
script: ./testall.sh
